/*
  ============================================================
  ★ 問題データファイル ★
  quiz-game.html と同じフォルダに置いてください。

  【問題のtype】
    type: "yontaku"  → 4択問題
    type: "hayaoshi" → 早押し問題
    type: "kizyutsu" → 記述式問題
    type: "jiyuu"    → 自由回答問題
  ============================================================
*/
const DEFAULT_GENRES = [
  {
    id: "heiwa",
    name: "HEIWA",
    logo: "images/logo/heiwa_logo.png",
    logoText: "HEIWA",
    desc: "平和パチスロのクイズ",
    color: "#ff6600",
    questions: [
      { id:1, type:"yontaku", title:"このキャラクターの名前は？", text:"このキャラクターの名前は何でしょう？", media:"images/heiwa/q1.png", audio:null, choices:["スヌーピー","グミ","定春","シロ"], correct:3, explanation:null },
      { id:2, type:"yontaku", title:"このキャラクターの必殺技は？①", text:"織田信長の必殺技は？", media:"images/heiwa/q2.png", audio:null, choices:["紅蓮爆炎刃","地獄ノ火炎","非情ノ大剣","闘気炎斬剣"], correct:2, explanation:null },
      { id:3, type:"hayaoshi", title:"早押し：HEIWAの代表作は？", text:"平和（HEIWA）が手がけた、CR機の大ヒット作で「○○○伝説」と呼ばれるシリーズといえば何でしょう？", media:null, audio:null, answer:"CR花満開", explanation:"CR花満開シリーズは平和の代表的なヒット作です。" }
    ]
  },
  {
    id: "sanyo",
    name: "SANYO",
    logo: "images/logo/sanyo_logo.png",
    logoText: "SANYO",
    desc: "三洋物産のクイズ",
    color: "#0088ff",
    questions: [
      { id:1, type:"yontaku", title:"山陽新幹線の終点は？", text:"山陽新幹線の終点はどこでしょう？", media:null, audio:null, choices:["広島駅","岡山駅","博多駅","下関駅"], correct:2, explanation:"山陽新幹線は新大阪駅から博多駅を結んでいます。1975年に全線開業しました。" },
      { id:2, type:"yontaku", title:"瀬戸内海の世界遺産の島は？", text:"瀬戸内海に浮かぶ世界遺産の島はどこでしょう？", media:null, audio:null, choices:["小豆島","宮島（厳島）","淡路島","直島"], correct:1, explanation:"宮島（厳島）は厳島神社が世界遺産に登録されています。" },
      { id:3, type:"yontaku", title:"岡山県の白桃は全国何位？", text:"岡山県の名産品「白桃」の生産量は全国何位でしょう？", media:null, audio:null, choices:["1位","2位","3位","4位"], correct:0, explanation:"岡山県は白桃の生産量が全国1位です。" },
      { id:4, type:"hayaoshi", title:"早押し：SANYOの名機は？", text:"三洋物産が2004年にリリースし、爆発的な人気を誇ったスロット「○○○祭り」の正式名称は何でしょう？", media:null, audio:null, answer:"吉宗", explanation:"「吉宗」は三洋物産の大ヒット作で、設定6のスペックが話題になりました。" }
    ]
  },
  {
    id: "character",
    name: "キャラクタークイズ",
    logo: null,
    logoText: "CHARACTER",
    desc: "このキャラクターの名前は？",
    color: "#cc44ff",
    questions: [
      { id:1, type:"kizyutsu", title:"Q1 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q1.png", audio:null, answer:"典韋（一騎当千）", answers:"典韋（一騎当千）", nagaoType:"未分類", explanation:null },
      { id:2, type:"kizyutsu", title:"Q2 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q2.png", audio:null, answer:"趙雲子龍（一騎当千）", answers:"趙雲子龍（一騎当千）", nagaoType:"未分類", explanation:null },
      { id:3, type:"kizyutsu", title:"Q3 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q3.png", audio:null, answer:"木下ベッカム（ペンギンの問題）", answers:"木下ベッカム（ペンギンの問題）", nagaoType:"未分類", explanation:null },
      { id:4, type:"kizyutsu", title:"Q4 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q4.png", audio:null, answer:"サンダース（MAJOR）", answers:"サンダース（MAJOR）", nagaoType:"未分類", explanation:null },
      { id:5, type:"kizyutsu", title:"Q5 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q5.png", audio:null, answer:"眉村健（MAJOR）", answers:"眉村健（MAJOR）", nagaoType:"未分類", explanation:null },
      { id:6, type:"kizyutsu", title:"Q6 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q6.png", audio:null, answer:"サイバスター（スパロボOG）", answers:"サイバスター（スパロボOG）", nagaoType:"未分類", explanation:null },
      { id:7, type:"kizyutsu", title:"Q7 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q7.png", audio:null, answer:"凰鈴音（IS）", answers:"凰鈴音（IS）", nagaoType:"未分類", explanation:null },
      { id:8, type:"kizyutsu", title:"Q8 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q8.png", audio:null, answer:"シャルロット・デュノア（IS）", answers:"シャルロット・デュノア（IS）", nagaoType:"未分類", explanation:null },
      { id:9, type:"kizyutsu", title:"Q9 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q9.png", audio:null, answer:"東条英虎（べるぜバブ）", answers:"東条英虎（べるぜバブ）", nagaoType:"未分類", explanation:null },
      { id:10, type:"kizyutsu", title:"Q10 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q10.png", audio:null, answer:"邦枝葵（べるぜバブ）", answers:"邦枝葵（べるぜバブ）", nagaoType:"未分類", explanation:null },
      { id:11, type:"kizyutsu", title:"Q11 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q11.png", audio:null, answer:"ユークリウッド・ヘルサイズ（これゾン）", answers:"ユークリウッド・ヘルサイズ（これゾン）", nagaoType:"未分類", explanation:null },
      { id:12, type:"kizyutsu", title:"Q12 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q12.png", audio:null, answer:"大先生・アリエル（これゾン）", answers:"大先生・アリエル（これゾン）", nagaoType:"未分類", explanation:null },
      { id:13, type:"kizyutsu", title:"Q13 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q13.png", audio:null, answer:"リボンちゃん（ハム太郎）", answers:"リボンちゃん（ハム太郎）", nagaoType:"未分類", explanation:null },
      { id:14, type:"kizyutsu", title:"Q14 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q14.png", audio:null, answer:"タイショーくん（ハム太郎）", answers:"タイショーくん（ハム太郎）", nagaoType:"未分類", explanation:null },
      { id:15, type:"kizyutsu", title:"Q15 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q15.png", audio:null, answer:"春奈ヒロ子・ロコちゃん（ハム太郎）", answers:"春奈ヒロ子・ロコちゃん（ハム太郎）", nagaoType:"未分類", explanation:null },
      { id:16, type:"kizyutsu", title:"Q16 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q16.png", audio:null, answer:"神威（銀魂）", answers:"神威（銀魂）", nagaoType:"未分類", explanation:null },
      { id:17, type:"kizyutsu", title:"Q17 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q17.png", audio:null, answer:"志村新八（銀魂）", answers:"志村新八（銀魂）", nagaoType:"未分類", explanation:null },
      { id:18, type:"kizyutsu", title:"Q18 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q18.png", audio:null, answer:"クッキー（まじ恋）", answers:"クッキー（まじ恋）", nagaoType:"未分類", explanation:null },
      { id:19, type:"kizyutsu", title:"Q19 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q19.png", audio:null, answer:"明智光秀（織田信奈の野望）", answers:"明智光秀（織田信奈の野望）", nagaoType:"未分類", explanation:null },
      { id:20, type:"kizyutsu", title:"Q20 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q20.png", audio:null, answer:"前田犬千代（織田信奈の野望）", answers:"前田犬千代（織田信奈の野望）", nagaoType:"未分類", explanation:null },
      { id:21, type:"kizyutsu", title:"Q21 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q21.png", audio:null, answer:"ねね（織田信奈の野望）", answers:"ねね（織田信奈の野望）", nagaoType:"未分類", explanation:null },
      { id:22, type:"kizyutsu", title:"Q22 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q22.png", audio:null, answer:"サチ（SAO）", answers:"サチ（SAO）", nagaoType:"未分類", explanation:null },
      { id:23, type:"kizyutsu", title:"Q23 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q23.png", audio:null, answer:"リズベット（SAO）", answers:"リズベット（SAO）", nagaoType:"未分類", explanation:null },
      { id:24, type:"kizyutsu", title:"Q24 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q24.png", audio:null, answer:"暁古城（ストライク・ザ・ブラッド）", answers:"暁古城（ストライク・ザ・ブラッド）", nagaoType:"未分類", explanation:null },
      { id:25, type:"kizyutsu", title:"Q25 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q25.png", audio:null, answer:"モグワイ（ストライク・ザ・ブラッド）", answers:"モグワイ（ストライク・ザ・ブラッド）", nagaoType:"未分類", explanation:null },
      { id:26, type:"kizyutsu", title:"Q26 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q26.png", audio:null, answer:"姫柊雪菜（ストライク・ザ・ブラッド）", answers:"姫柊雪菜（ストライク・ザ・ブラッド）", nagaoType:"未分類", explanation:null },
      { id:27, type:"kizyutsu", title:"Q27 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q27.png", audio:null, answer:"沢村栄純（ダイヤのA）", answers:"沢村栄純（ダイヤのA）", nagaoType:"未分類", explanation:null },
      { id:28, type:"kizyutsu", title:"Q28 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q28.png", audio:null, answer:"御幸一也（ダイヤのA）", answers:"御幸一也（ダイヤのA）", nagaoType:"未分類", explanation:null },
      { id:29, type:"kizyutsu", title:"Q29 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q29.png", audio:null, answer:"コン（東京レイヴンズ）", answers:"コン（東京レイヴンズ）", nagaoType:"未分類", explanation:null },
      { id:30, type:"kizyutsu", title:"Q30 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q30.png", audio:null, answer:"一条楽（ニセコイ）", answers:"一条楽（ニセコイ）", nagaoType:"未分類", explanation:null },
      { id:31, type:"kizyutsu", title:"Q31 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q31.png", audio:null, answer:"橘真里花（ニセコイ）", answers:"橘真里花（ニセコイ）", nagaoType:"未分類", explanation:null },
      { id:32, type:"kizyutsu", title:"Q32 このキャラクターの名前は？", text:"このキャラクターの名前は？", media:"images/character/q32.png", audio:null, answer:"桐崎千棘（ニセコイ）", answers:"桐崎千棘（ニセコイ）", nagaoType:"未分類", explanation:null }
    ]
  },
  {
    id: "pachi",
    name: "パチンコ関連",
    logo: null,
    logoText: "PACHI",
    desc: "",
    color: "#ff6600",
    questions: [
      { id:1, type:"yontaku", title:"海物語シリーズに登場する「マリン」の年齢は？", text:"海物語シリーズに登場する「マリン」の年齢は？", media:null, audio:null, choices:["15","16","18","20"], correct:2, explanation:null },
      { id:2, type:"yontaku", title:"海物語シリーズに登場する「ワリン」の年齢は？", text:"海物語シリーズに登場する「ワリン」の年齢は？", media:null, audio:null, choices:["16","18","20","22"], correct:1, explanation:null },
      { id:3, type:"yontaku", title:"海物語シリーズに登場する「ウリン」の年齢は？", text:"海物語シリーズに登場する「ウリン」の年齢は？", media:null, audio:null, choices:["11","12","15","16"], correct:2, explanation:null },
      { id:4, type:"kizyutsu", title:"P海物語 極JAPANに新キャラとして登場した狐の神様の名前は？", text:"P海物語 極JAPANに新キャラとして登場した狐の神様の名前は？", media:null, audio:null, answer:"火鈴（カリン）", answers:"火鈴（カリン）,火鈴,カリン,かりん", nagaoType:"SANYO", explanation:null },
      { id:5, type:"kizyutsu", title:"海物語で2図柄を担当する海の生き物は？", text:"海物語で2図柄を担当する海の生き物は？", media:null, audio:null, answer:"ハリセンボン", answers:"ハリセンボン,はりせんぼん", nagaoType:"SANYO", explanation:null },
      { id:6, type:"kizyutsu", title:"海物語で6図柄を担当する海の生き物は？", text:"海物語で6図柄を担当する海の生き物は？", media:null, audio:null, answer:"アンコウ", answers:"アンコウ,あんこう", nagaoType:"SANYO", explanation:null },
      { id:7, type:"kizyutsu", title:"高速消化が流行ったときの代表的なSANYOの台は？（コンテンツ名）", text:"高速消化が流行ったときの代表的なSANYOの台は？（コンテンツ名）", media:null, audio:null, answer:"大工の源さん", answers:"大工の源さん,源さん,げんさん", nagaoType:"SANYO", explanation:null },
      { id:8, type:"kizyutsu", title:"海物語シリーズのプレミアキャラであり、その名前のパチンコ台も存在するキャラクターの名前は？", text:"海物語シリーズのプレミアキャラであり、その名前のパチンコ台も存在するキャラクターの名前は？", media:null, audio:null, answer:"クジラッキー", answers:"クジラッキー", nagaoType:"SANYO", explanation:null },
      { id:9, type:"kizyutsu", title:"大当り期待度が大幅にアップする激アツ予告演出で、画面の右から左へ大量の魚たちが群れをなして横切る演出を何というか？", text:"大当り期待度が大幅にアップする激アツ予告演出で、画面の右から左へ大量の魚たちが群れをなして横切る演出を何というか？", media:null, audio:null, answer:"魚群", answers:"魚群", nagaoType:"SANYO", explanation:null },
      { id:10, type:"yontaku", title:"次のうち、海物語シリーズのハイビスカスモードでリーチ目なのはどれ？", text:"次のうち、海物語シリーズのハイビスカスモードでリーチ目なのはどれ？", media:null, audio:null, choices:["773","491","813","118"], correct:2, explanation:null },
      { id:11, type:"kizyutsu", title:"Summyの機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"Summyの機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"キリン", answers:"キリン,きりん", nagaoType:"SUMMY", explanation:null },
      { id:12, type:"kizyutsu", title:"リーチが「海」「大地」「空」「魂」の順に期待度が高いパチンコのコンテンツは？", text:"リーチが「海」「大地」「空」「魂」の順に期待度が高いパチンコのコンテンツは？", media:null, audio:null, answer:"聖戦士ダンバイン", answers:"聖戦士ダンバイン,ダンバイン", nagaoType:"SUMMY", explanation:null },
      { id:13, type:"kizyutsu", title:"Summyのパチンコで先バレカスタムのことを主に何モードという？", text:"Summyのパチンコで先バレカスタムのことを主に何モードという？", media:null, audio:null, answer:"イキナリフラッシュ", answers:"イキナリフラッシュ,いきなりフラッシュ,イキナリフラッシュモード,いきなりフラッシュモード", nagaoType:"SUMMY", explanation:null },
      { id:14, type:"kizyutsu", title:"クレイジーギアが激しく震えた瞬間、当たりがほぼ確定になるカスタムは何モードという？", text:"クレイジーギアが激しく震えた瞬間、当たりがほぼ確定になるカスタムは何モードという？", media:null, audio:null, answer:"ギアクラッシュ", answers:"ギアクラッシュ,ギアクラッシュモード", nagaoType:"SUMMY", explanation:null },
      { id:15, type:"kizyutsu", title:"Summyの宇宙人の見た目をしたキャラクターの名前を正確に答えよ", text:"Summyの宇宙人の見た目をしたキャラクターの名前を正確に答えよ", media:null, audio:null, answer:"エイリやん", answers:"エイリやん", nagaoType:"SUMMY", explanation:null },
      { id:16, type:"kizyutsu", title:"ショウ・ザマのパートナーであるミ・フェラリオ種の名前は？", text:"ショウ・ザマのパートナーであるミ・フェラリオ種の名前は？", media:null, audio:null, answer:"チャム・ファウ", answers:"チャム・ファウ, チャム", nagaoType:"SUMMY", explanation:null },
      { id:17, type:"kizyutsu", title:"北斗羅漢撃を必殺技として使うキャラクターは？", text:"北斗羅漢撃を必殺技として使うキャラクターは？", media:null, audio:null, answer:"ジャギ", answers:"ジャギ", nagaoType:"SUMMY", explanation:null },
      { id:18, type:"kizyutsu", title:"サブタイトルに「真の約束の地」「ANEMONE」「HI-EVOLUTION」とタイトルにつくコンテンツは？", text:"サブタイトルに「真の約束の地」「ANEMONE」「HI-EVOLUTION」とタイトルにつくコンテンツは？", media:null, audio:null, answer:"交響詩篇エウレカセブン", answers:"交響詩篇エウレカセブン,エウレカセブン,エウレカ", nagaoType:"SUMMY", explanation:null },
      { id:19, type:"yontaku", title:"Pゾンビランドサガの初当たり確率は？", text:"Pゾンビランドサガの初当たり確率は？", media:null, audio:null, choices:["1/149.9","1/159.8","1/199.8","1/239.1"], correct:1, explanation:null },
      { id:20, type:"yontaku", title:"次のうち、導入が最も新しいのは？", text:"次のうち、導入が最も新しいのは？", media:null, audio:null, choices:["Pゾンビランドサガ","Pブラックラグーン4","Pモンスターハンターライズ","P盾の勇者の成り上がり"], correct:0, explanation:null },
      { id:21, type:"kizyutsu", title:"藤商事のマントを羽織っているオリジナルキャラを正確に答えよ", text:"藤商事のマントを羽織っているオリジナルキャラを正確に答えよ", media:null, audio:null, answer:"藤丸くん", answers:"藤丸くん", nagaoType:"FUJISHOJI", explanation:null },
      { id:22, type:"kizyutsu", title:"藤商事の台で先バレのことを主になんと呼ぶ？", text:"藤商事の台で先バレのことを主になんと呼ぶ？", media:null, audio:null, answer:"先ローリング", answers:"先ローリング,先ロリ", nagaoType:"FUJISHOJI", explanation:null },
      { id:23, type:"kizyutsu", title:"藤商事の機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"藤商事の機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"DANGER", answers:"DANGER,danger,デンジャー", nagaoType:"FUJISHOJI", explanation:null },
      { id:24, type:"yontaku", title:"次のうち、筐体に電話がついている台はどれ？", text:"次のうち、筐体に電話がついている台はどれ？", media:null, audio:null, choices:["P貞子","Pリング 呪いの7日間2","Pリング バースデイ 呪いの始まり","Pリング呪縛RUSH"], correct:2, explanation:null },
      { id:25, type:"kizyutsu", title:"CR機で漫画のコマが筐体に付いており、ステップ演出がそのコマで告知された台のコンテンツ名を答えよ。", text:"CR機で漫画のコマが筐体に付いており、ステップ演出がそのコマで告知された台のコンテンツ名を答えよ。", media:null, audio:null, answer:"FAILY TAIL", answers:"FAILY TAIL,faily tail,フェアリーテイル", nagaoType:"FUJISHOJI", explanation:null },
      { id:26, type:"kizyutsu", title:"とあるシリーズなどに搭載されているカスタムの一つで、画面に表示されている数だけボタンを押すことができ、当たっていればどこかのタイミングで確定音がなるモードは何？", text:"とあるシリーズなどに搭載されているカスタムの一つで、画面に表示されている数だけボタンを押すことができ、当たっていればどこかのタイミングで確定音がなるモードは何？", media:null, audio:null, answer:"ラッキーパトモード", answers:"ラッキーパトモード,ラッキーパト", nagaoType:"FUJISHOJI", explanation:null },
      { id:27, type:"kizyutsu", title:"とあるシリーズで水着ステージで美味しい料理が作れれば当たりの演出があります。その料理とは何でしょう？", text:"とあるシリーズで水着ステージで美味しい料理が作れれば当たりの演出があります。その料理とは何でしょう？", media:null, audio:null, answer:"カレー", answers:"カレー", nagaoType:"FUJISHOJI", explanation:null },
      { id:28, type:"yontaku", title:"次のうち、とある科学の超電磁砲PHASE NEXTで信頼度が最も高い保留はどれ？", text:"次のうち、とある科学の超電磁砲PHASE NEXTで信頼度が最も高い保留はどれ？", media:null, audio:null, choices:["ピンク","LEVEL5","お姉さまLOVE","青"], correct:3, explanation:null },
      { id:29, type:"yontaku", title:"フェアリーテイルシリーズで5図柄のキャラは次のうち誰？", text:"フェアリーテイルシリーズで5図柄のキャラは次のうち誰？", media:null, audio:null, choices:["ルーシィ","エルザ","グレイ","ウェンディ"], correct:1, explanation:null },
      { id:30, type:"kizyutsu", title:"ヒステリアモードを搭載したコンテンツの名前は？", text:"ヒステリアモードを搭載したコンテンツの名前は？", media:null, audio:null, answer:"緋弾のアリア", answers:"緋弾のアリア,アリア", nagaoType:"FUJISHOJI", explanation:null },
      { id:31, type:"kizyutsu", title:"激熱カットインには「萌え」や「激エモ」など複数ありますが、『戦国恋姫』シリーズの何カットインと呼ばれる？", text:"激熱カットインには「萌え」や「激エモ」など複数ありますが、『戦国恋姫』シリーズの何カットインと呼ばれる？", media:null, audio:null, answer:"俺の嫁", answers:"俺の嫁,俺の嫁カットイン", nagaoType:"KYORAKU", explanation:null },
      { id:32, type:"kizyutsu", title:"ハンドルから風が出る仕組みをなんと呼ぶ？", text:"ハンドルから風が出る仕組みをなんと呼ぶ？", media:null, audio:null, answer:"Air-Vib（エアバイブ）", answers:"Air-Vib（エアバイブ）,Air-Vib,air-vib,エアバイブ", nagaoType:"KYORAKU", explanation:null },
      { id:33, type:"kizyutsu", title:"e魔法少女まどか☆マギカ3に搭載されている、当該変動がハズレの場合に演出だけでなく、完全にスキップして強制的に終わらせる機能を何という？", text:"e魔法少女まどか☆マギカ3に搭載されている、当該変動がハズレの場合に演出だけでなく、完全にスキップして強制的に終わらせる機能を何という？", media:null, audio:null, answer:"P-スキップ", answers:"P-スキップ,Pスキップ,PSKIP,P SKIP,P スキップ,p-スキップ,pスキップ,p スキップ,pskip,p skip", nagaoType:"KYORAKU", explanation:null },
      { id:34, type:"yontaku", title:"アズールレーンのパチンコにおいて、裏カスタム・隠しモードを強制的に解放するにはカスタムメニューで○ボタンを何回プッシュすれば良いか？", text:"アズールレーンのパチンコにおいて、裏カスタム・隠しモードを強制的に解放するにはカスタムメニューで○ボタンを何回プッシュすれば良いか？", media:null, audio:null, choices:["2","3","5","8"], correct:3, explanation:null },
      { id:35, type:"kizyutsu", title:"SAOのパチンコにおいて、右打ち中の演出中に出現すれば当たりになる発見告知のキャラクターの名前は？", text:"SAOのパチンコにおいて、右打ち中の演出中に出現すれば当たりになる発見告知のキャラクターの名前は？", media:null, audio:null, answer:"エギル", answers:"エギル,えぎる", nagaoType:"KYORAKU", explanation:null },
      { id:36, type:"kizyutsu", title:"京楽の機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"京楽の機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"ゼブラ", answers:"ゼブラ", nagaoType:"KYORAKU", explanation:null },
      { id:37, type:"yontaku", title:"小当たりRUShが初めて導入されたのは次のうちどれ？", text:"小当たりRUShが初めて導入されたのは次のうちどれ？", media:null, audio:null, choices:["CRぱちんこGANTS 3(319ver)","CRフィーバーLADY GAGA R","CRウルトラセブン2","CRぱちんこ必殺仕事人V"], correct:0, explanation:null },
      { id:38, type:"yontaku", title:"京楽のキャラクター「たぬ吉」の胸に描いてある文字は次のうちどれ？", text:"京楽のキャラクター「たぬ吉」の胸に描いてある文字は次のうちどれ？", media:null, audio:null, choices:["京","V","楽","た"], correct:3, explanation:null },
      { id:39, type:"yontaku", title:"AKB48のパチンコに搭載されているPUSHボタンについて、特徴が最も適しているのは次のうちどれ？", text:"AKB48のパチンコに搭載されているPUSHボタンについて、特徴が最も適しているのは次のうちどれ？", media:null, audio:null, choices:["絵や文字が流れる","形がペンライト","やわらかい","ボタンが二つある"], correct:2, explanation:null },
      { id:40, type:"kizyutsu", title:"京楽のパチンコに搭載されているPUSHボタンからレバーへと変形するデバイスを何トリガーというか？", text:"京楽のパチンコに搭載されているPUSHボタンからレバーへと変形するデバイスを何トリガーというか？", media:null, audio:null, answer:"ライジングトリガー", answers:"ライジングトリガー,ライジング", nagaoType:"KYORAKU", explanation:null },
      { id:41, type:"kizyutsu", title:"京楽のパチンコで、二つのハンドルやPUSHボタンからレバーへと変形するデバイスが搭載されている筐体を何枠というか？", text:"京楽のパチンコで、二つのハンドルやPUSHボタンからレバーへと変形するデバイスが搭載されている筐体を何枠というか？", media:null, audio:null, answer:"ベルーガ枠", answers:"ベルーガ枠.ベルーガ", nagaoType:"KYORAKU", explanation:null },
      { id:42, type:"yontaku", title:"次のうち、2図柄を担ったことのないキャラクターはどれ？", text:"次のうち、2図柄を担ったことのないキャラクターはどれ？", media:null, audio:null, choices:["室生オウガイ","大友ソウリン","上杉ケンシン","今川ヨシモト"], correct:3, explanation:null },
      { id:43, type:"kizyutsu", title:"戦国乙女に登場するムラサメという女性の苗字を漢字で答えよ", text:"戦国乙女に登場するムラサメという女性の苗字を漢字で答えよ", media:null, audio:null, answer:"斉藤", answers:"斉藤", nagaoType:"HEIWA", explanation:null },
      { id:44, type:"kizyutsu", title:"戦国乙女で電サポ終了して左打ちに戻ったときに突入するステージは何モードという？", text:"戦国乙女で電サポ終了して左打ちに戻ったときに突入するステージは何モードという？", media:null, audio:null, answer:"もっとときめきモード", answers:"もっとときめきモード,もっとときめき", nagaoType:"HEIWA", explanation:null },
      { id:45, type:"kizyutsu", title:"平和の筐体の右側に付いているランプが発光することを何フラッシュという？", text:"平和の筐体の右側に付いているランプが発光することを何フラッシュという？", media:null, audio:null, answer:"ピースフラッシュ", answers:"ピースフラッシュ,ピース", nagaoType:"HEIWA", explanation:null },
      { id:46, type:"kizyutsu", title:"Pバンドリ！のST突入確率は何%？", text:"Pバンドリ！のST突入確率は何%？", media:null, audio:null, answer:"1", answers:"100%,100,１００,100％,１００％", nagaoType:"HEIWA", explanation:null },
      { id:47, type:"yontaku", title:"P黄門ちゃま寿限無で導入されていないスペックは？(2026/7時点)", text:"P黄門ちゃま寿限無で導入されていないスペックは？(2026/7時点)", media:null, audio:null, choices:["99","199","259","399"], correct:1, explanation:null },
      { id:48, type:"kizyutsu", title:"ジョディ・バーンサイド(南国育ち)、今川ヨシモト(戦国乙女)、風上まどか(麻雀物語)、織田ノブナガ(戦国乙女)、姿月レイコ(南国育ち)で構成されたセクシー系和風ユニットのユニット名は？", text:"ジョディ・バーンサイド(南国育ち)、今川ヨシモト(戦国乙女)、風上まどか(麻雀物語)、織田ノブナガ(戦国乙女)、姿月レイコ(南国育ち)で構成されたセクシー系和風ユニットのユニット名は？", media:null, audio:null, answer:"天照", answers:"天照,アマテラス,あまてらす", nagaoType:"HEIWA", explanation:null },
      { id:49, type:"kizyutsu", title:"CR烈火の炎2に搭載られている16R2400発に加えてさらに出玉を獲得できるシステムを何ユニットと呼ぶ？", text:"CR烈火の炎2に搭載られている16R2400発に加えてさらに出玉を獲得できるシステムを何ユニットと呼ぶ？", media:null, audio:null, answer:"バーニングユニット", answers:"バーニングユニット,バーニング", nagaoType:"HEIWA", explanation:null },
      { id:50, type:"yontaku", title:"ヘソ入賞しているのに変動が開始しないバグがあった台は次のうちどれ？", text:"ヘソ入賞しているのに変動が開始しないバグがあった台は次のうちどれ？", media:null, audio:null, choices:["CR戦国乙女〜花〜","CR麻雀物語2","CR銀河鉄道999","CRターミネーター2"], correct:0, explanation:null },
      { id:51, type:"kizyutsu", title:"平和のパチンコ機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"平和のパチンコ機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"トラ", answers:"トラ,とら,虎", nagaoType:"HEIWA", explanation:null },
      { id:52, type:"kizyutsu", title:"Pうまい棒に搭載されている、めんたいフラッシュ当たり期待度90%超となるモードは何味？", text:"Pうまい棒に搭載されている、めんたいフラッシュ当たり期待度90%超となるモードは何味？", media:null, audio:null, answer:"先うま味", answers:"先うま味,先うま", nagaoType:"AMTECS", explanation:null },
      { id:53, type:"kizyutsu", title:"Pうまい棒に搭載されている、パトランプが光れば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、パトランプが光れば当たりとなるモードは何味？", media:null, audio:null, answer:"パトランプ味", answers:"パトランプ味,パトランプ", nagaoType:"AMTECS", explanation:null },
      { id:54, type:"kizyutsu", title:"Pうまい棒に搭載されている、うまい棒を開けることができれば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、うまい棒を開けることができれば当たりとなるモードは何味？", media:null, audio:null, answer:"開封味", answers:"開封味,開封", nagaoType:"AMTECS", explanation:null },
      { id:55, type:"kizyutsu", title:"Pうまい棒に搭載されている、ファンファーレが鳴れば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、ファンファーレが鳴れば当たりとなるモードは何味？", media:null, audio:null, answer:"爆音味", answers:"爆音味,爆音", nagaoType:"AMTECS", explanation:null },
      { id:56, type:"kizyutsu", title:"Pうまい棒に搭載されている、ステップアップ式で、うまみちゃんがセリフを全て言えたら当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、ステップアップ式で、うまみちゃんがセリフを全て言えたら当たりとなるモードは何味？", media:null, audio:null, answer:"大人味", answers:"大人味,大人", nagaoType:"AMTECS", explanation:null },
      { id:57, type:"kizyutsu", title:"Pうまい棒に搭載されている、蝶が飛んでランプが発行すれば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、蝶が飛んでランプが発行すれば当たりとなるモードは何味？", media:null, audio:null, answer:"南国味", answers:"南国味,南国", nagaoType:"AMTECS", explanation:null },
      { id:58, type:"kizyutsu", title:"Pうまい棒に搭載されている、うまみちゃんが目を覚ませば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、うまみちゃんが目を覚ませば当たりとなるモードは何味？", media:null, audio:null, answer:"おはよう味", answers:"おはよう味,おはよう", nagaoType:"AMTECS", explanation:null },
      { id:59, type:"kizyutsu", title:"Pうまい棒に搭載されている、うまみちゃんがサビまで歌い切れたら当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、うまみちゃんがサビまで歌い切れたら当たりとなるモードは何味？", media:null, audio:null, answer:"熱唱味", answers:"熱唱味,熱唱", nagaoType:"AMTECS", explanation:null },
      { id:60, type:"kizyutsu", title:"Pうまい棒に搭載されている、ボタンが震えれば当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、ボタンが震えれば当たりとなるモードは何味？", media:null, audio:null, answer:"ぶるぶる味", answers:"ぶるぶる味,ぶるぶる", nagaoType:"AMTECS", explanation:null },
      { id:61, type:"kizyutsu", title:"Pうまい棒に搭載されている、ボタンを押して画面のうまい棒開封または告知棒飛び出しで当たりとなるモードは何味？", text:"Pうまい棒に搭載されている、ボタンを押して画面のうまい棒開封または告知棒飛び出しで当たりとなるモードは何味？", media:null, audio:null, answer:"光棒味", answers:"光棒味,光棒", nagaoType:"AMTECS", explanation:null },
      { id:62, type:"kizyutsu", title:"SANKYOのパチンコ機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"SANKYOのパチンコ機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"フルーツ柄", answers:"フルーツ柄,フルーツ", nagaoType:"SANKYO", explanation:null },
      { id:63, type:"kizyutsu", title:"『フィーバーパワフル』で初登場した、現在はプレミアキャラとして扱われるSANKYO永遠のアイドルキャラクターは？", text:"『フィーバーパワフル』で初登場した、現在はプレミアキャラとして扱われるSANKYO永遠のアイドルキャラクターは？", media:null, audio:null, answer:"夢夢ちゃん", answers:"夢夢ちゃん", nagaoType:"SANKYO", explanation:null },
      { id:64, type:"kizyutsu", title:"SANKYOのパチンコ機において、発生した時点で大当たりやRUSHが確定となるプレミア演出を何という？", text:"SANKYOのパチンコ機において、発生した時点で大当たりやRUSHが確定となるプレミア演出を何という？", media:null, audio:null, answer:"V-フラッシュ", answers:"V-フラッシュ,Vフラッシュ,Vフラ", nagaoType:"SANKYO", explanation:null },
      { id:65, type:"kizyutsu", title:"『eフィーバー彼女、お借りします』において、通常時に約30%の割合で当選する2Rのチャージ大当りの名称は何？", text:"『eフィーバー彼女、お借りします』において、通常時に約30%の割合で当選する2Rのチャージ大当りの名称は何？", media:null, audio:null, answer:"ヒロイン劇場", answers:"ヒロイン劇場", nagaoType:"SANKYO", explanation:null },
      { id:66, type:"yontaku", title:"『Pフィーバー機動戦士ガンダムSEED』で通常時短の時より大当たり確率は次のうちどれ？", text:"『Pフィーバー機動戦士ガンダムSEED』で通常時短の時より大当たり確率は次のうちどれ？", media:null, audio:null, choices:["1/319.9","1/429.1","1/538.8","1/601.3"], correct:3, explanation:null },
      { id:67, type:"kizyutsu", title:"『eフィーバーブルーロック』の先バレの期待度を変化かせるカスタムを何カスタムという？", text:"『eフィーバーブルーロック』の先バレの期待度を変化かせるカスタムを何カスタムという？", media:null, audio:null, answer:"先エゴイストカスタム", answers:"先エゴイストカスタム,先エゴイスト", nagaoType:"SANKYO", explanation:null },
      { id:68, type:"yontaku", title:"次の中で、『eフィーバー炎炎ノ消防隊2 紅丸ver.』の保留で最も信頼度が高いものを選べ", text:"次の中で、『eフィーバー炎炎ノ消防隊2 紅丸ver.』の保留で最も信頼度が高いものを選べ", media:null, audio:null, choices:["金保留","アイリス保留","紅丸保留","赤シンラ保留"], correct:1, explanation:null },
      { id:69, type:"kizyutsu", title:"〇〇アタックとリーチ演出の名前にもなっているガンダムSEEDに登場する戦艦の名前は？", text:"〇〇アタックとリーチ演出の名前にもなっているガンダムSEEDに登場する戦艦の名前は？", media:null, audio:null, answer:"アークエンジェル", answers:"アークエンジェル", nagaoType:"SANKYO", explanation:null },
      { id:70, type:"kizyutsu", title:"機動戦士ガンダムユニコーンシリーズにすべて収録られている3大演出は「赤い彗星の再来ゾーン」「ガンダムユニコーン予告」ともう一つは何？", text:"機動戦士ガンダムユニコーンシリーズにすべて収録られている3大演出は「赤い彗星の再来ゾーン」「ガンダムユニコーン予告」ともう一つは何？", media:null, audio:null, answer:"可能性の獣", answers:"可能性の獣", nagaoType:"SANKYO", explanation:null },
      { id:71, type:"kizyutsu", title:"高尾のパチンコ機で「⼊るんスタート」を初めて搭載したコンテンツは何？", text:"高尾のパチンコ機で「⼊るんスタート」を初めて搭載したコンテンツは何？", media:null, audio:null, answer:"織田信奈の野望", answers:"織田信奈の野望", nagaoType:"TAKAO", explanation:null },
      { id:72, type:"kizyutsu", title:"高尾のパチンコ機でプレミアキャラとして出現する、ある動物をモチーフとしたメーカーオリジナルキャラクターの名前は？", text:"高尾のパチンコ機でプレミアキャラとして出現する、ある動物をモチーフとしたメーカーオリジナルキャラクターの名前は？", media:null, audio:null, answer:"キレパンダ", answers:"キレパンダ", nagaoType:"TAKAO", explanation:null },
      { id:73, type:"kizyutsu", title:"ノーゲーム・ノーライフや学園黙示録ハイスクール・オブ・ザ・デッド3など、高尾の新筐体のカスタムに搭載された先バレに相当するモードを何という？", text:"ノーゲーム・ノーライフや学園黙示録ハイスクール・オブ・ザ・デッド3など、高尾の新筐体のカスタムに搭載された先バレに相当するモードを何という？", media:null, audio:null, answer:"先ギレ", answers:"先ギレ", nagaoType:"TAKAO", explanation:null },
      { id:74, type:"kizyutsu", title:"『クイーンズブレイド』シリーズに登場する、美闘士がM字開脚（V字もある）を決めたら大チャンスとなる演出名は？", text:"『クイーンズブレイド』シリーズに登場する、美闘士がM字開脚（V字もある）を決めたら大チャンスとなる演出名は？", media:null, audio:null, answer:"聖なるポーズ", answers:"聖なるポーズ,聖なる", nagaoType:"TAKAO", explanation:null },
      { id:75, type:"kizyutsu", title:"高尾が作成したパチンコ（CR機）で、あるマーベルヒーローをメインとしたものがある。このヒーローとは誰？", text:"高尾が作成したパチンコ（CR機）で、あるマーベルヒーローをメインとしたものがある。このヒーローとは誰？", media:null, audio:null, answer:"スパイダーマン", answers:"スパイダーマン", nagaoType:"TAKAO", explanation:null },
      { id:76, type:"kizyutsu", title:"『真・一騎当千』などに搭載されているカスタムで、胸のサイズや動きによって期待度が変化するカスタムを何モードという？", text:"『真・一騎当千』などに搭載されているカスタムで、胸のサイズや動きによって期待度が変化するカスタムを何モードという？", media:null, audio:null, answer:"ぷるバレモード", answers:"ぷるバレモード,ぷるバレ", nagaoType:"DAIICHI", explanation:null },
      { id:77, type:"kizyutsu", title:"DaiichiやD-lightの機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", text:"DaiichiやD-lightの機種において、発生すると大当たり期待度が爆上がりするメーカー柄は何柄という？", media:null, audio:null, answer:"てんとう虫柄", answers:"てんとう虫柄,てんとう虫,テントウ虫,てんとうむし,テントウムシ", nagaoType:"DAIICHI", explanation:null },
      { id:78, type:"kizyutsu", title:"エヴァシリーズで、出現した時点で大当たりおよび確変が確定するキャラクターをフルネームで答えよ", text:"エヴァシリーズで、出現した時点で大当たりおよび確変が確定するキャラクターをフルネームで答えよ", media:null, audio:null, answer:"渚カヲル", answers:"渚カヲル", nagaoType:"BISTY", explanation:null },
      { id:79, type:"kizyutsu", title:"エヴァシリーズで、移行した時点で大当たりおよび確変が確定するステージ背景は何？", text:"エヴァシリーズで、移行した時点で大当たりおよび確変が確定するステージ背景は何？", media:null, audio:null, answer:"格納庫", answers:"格納庫", nagaoType:"BISTY", explanation:null },
      { id:80, type:"kizyutsu", title:"『新世紀エヴァンゲリオン ～未来への咆哮～』から搭載された、筐体の中央に配置された左右どちらの手でも操作可能なハンドルを何ハンドルという？", text:"『新世紀エヴァンゲリオン ～未来への咆哮～』から搭載された、筐体の中央に配置された左右どちらの手でも操作可能なハンドルを何ハンドルという？", media:null, audio:null, answer:"スマートハンドル", answers:"スマートハンドル,スマート", nagaoType:"BISTY", explanation:null },
      { id:81, type:"kizyutsu", title:"パチンコで、大当りをしたときに開いて、玉が入る部分を何と呼ぶ？", text:"パチンコで、大当りをしたときに開いて、玉が入る部分を何と呼ぶ？", media:null, audio:null, answer:"アタッカー", answers:"アタッカー", nagaoType:"ALL", explanation:null },
      { id:82, type:"kizyutsu", title:"確変状態である「ST」の正称をカタカナで答えよ", text:"確変状態である「ST」の正称をカタカナで答えよ", media:null, audio:null, answer:"スペシャルタイム", answers:"スペシャルタイム", nagaoType:"ALL", explanation:null },
      { id:83, type:"kizyutsu", title:"「スマパチ」の正称を答えよ", text:"「スマパチ」の正称を答えよ", media:null, audio:null, answer:"スマートパチンコ", answers:"スマートパチンコ", nagaoType:"ALL", explanation:null },
      { id:84, type:"kizyutsu", title:"パチンコのリーチアクションの一つで、絵柄が3つ揃った状態で変動する演出を何という？", text:"パチンコのリーチアクションの一つで、絵柄が3つ揃った状態で変動する演出を何という？", media:null, audio:null, answer:"全回転", answers:"全回転", nagaoType:"ALL", explanation:null },
      { id:85, type:"kizyutsu", title:"「電チュー」の正称を答えよ", text:"「電チュー」の正称を答えよ", media:null, audio:null, answer:"電子チューリップ", answers:"電子チューリップ", nagaoType:"ALL", explanation:null },
      { id:86, type:"kizyutsu", title:"釘に球が挟まり、次に打った玉がその上に重なり、盤面上がパチンコ玉だらけになることを、その見た目から何と呼ぶ？", text:"釘に球が挟まり、次に打った玉がその上に重なり、盤面上がパチンコ玉だらけになることを、その見た目から何と呼ぶ？", media:null, audio:null, answer:"ブドウ", answers:"ブドウ,ぶどう,葡萄", nagaoType:"ALL", explanation:null },
      { id:87, type:"kizyutsu", title:"主に大当り確率が1/100以下の甘パチや羽根モノ等の遊技機はまとめて何と呼ばれる？", text:"主に大当り確率が1/100以下の甘パチや羽根モノ等の遊技機はまとめて何と呼ばれる？", media:null, audio:null, answer:"遊パチ", answers:"遊パチ,遊ぱち", nagaoType:"ALL", explanation:null },
      { id:88, type:"kizyutsu", title:"2024年3月からパチンコに導入された、一定条件を満たしたとき、通常の遊技状態とは異なる高い出玉性能を持つ展開へつながる機能を何と呼ぶ？", text:"2024年3月からパチンコに導入された、一定条件を満たしたとき、通常の遊技状態とは異なる高い出玉性能を持つ展開へつながる機能を何と呼ぶ？", media:null, audio:null, answer:"ラッキートリガー", answers:"ラッキートリガー,LT", nagaoType:"ALL", explanation:null },
      { id:89, type:"kizyutsu", title:"ほとんどの液晶のパチンコ機で、ほとんど常に表示されている文字は何？", text:"ほとんどの液晶のパチンコ機で、ほとんど常に表示されている文字は何？", media:null, audio:null, answer:"右打ち", answers:"右打ち", nagaoType:"ALL", explanation:null },
      { id:90, type:"kizyutsu", title:"パチンコにおいて、通常時に大当りしないまま決まった回転数に達すると、自動で「時短」に入る救済機能を何という？", text:"パチンコにおいて、通常時に大当りしないまま決まった回転数に達すると、自動で「時短」に入る救済機能を何という？", media:null, audio:null, answer:"遊タイム", answers:"遊タイム", nagaoType:"ALL", explanation:null }
    ]
  },
  {
    id: "nagao",
    name: "軍団長からの挑戦状",
    logo: null,
    logoText: "NAGAO",
    desc: "軍団長・長尾が知っている物について答えよ",
    color: "#ff2244",
    questions: [
      { id:1, type:"kizyutsu", title:"Q1", text:"「鬼滅の刃」の主人公の名前は？", media:null, audio:null, answer:"竈門炭治郎", answers:"竈門炭治郎,かまどたんじろう,炭治郎", nagaoType:"アニメ", explanation:null },
      { id:2, type:"kizyutsu", title:"Q2", text:"「進撃の巨人」でエレンたちが暮らす壁の一番外側の名前は？", media:null, audio:null, answer:"ウォール・マリア", answers:"ウォール・マリア,ウォールマリア,マリア", nagaoType:"アニメ", explanation:null },
      { id:3, type:"kizyutsu", title:"Q3", text:"「ワンピース」でルフィが食べた悪魔の実の名前は？", media:null, audio:null, answer:"ゴムゴムの実", answers:"ゴムゴムの実,ごむごむのみ,ごむごむ,ゴムゴム", nagaoType:"マンガ", explanation:null },
      { id:4, type:"kizyutsu", title:"Q4", text:"「NARUTO」でナルトが最も得意とする忍術は？", media:null, audio:null, answer:"影分身の術", answers:"影分身の術,かげぶんしんのじゅつ,影分身", nagaoType:"マンガ", explanation:null },
      { id:5, type:"kizyutsu", title:"Q5", text:"「ドラゴンボール」で戦闘力が「53万」の敵は誰？", media:null, audio:null, answer:"フリーザ", answers:"フリーザ", nagaoType:"アニメ", explanation:null },
      { id:6, type:"kizyutsu", title:"Q6", text:"「銀魂」の主人公・坂田銀時が持つ木刀の名前は？", media:null, audio:null, answer:"洞爺湖", answers:"洞爺湖,とうやこ", nagaoType:"マンガ", explanation:null },
      { id:7, type:"kizyutsu", title:"Q7", text:"「僕のヒーローアカデミア」で緑谷出久の個性の名前は？", media:null, audio:null, answer:"ワン・フォー・オール", answers:"ワン・フォー・オール,ワンフォーオール", nagaoType:"アニメ", explanation:null },
      { id:8, type:"kizyutsu", title:"Q8", text:"「鋼の錬金術師」でエドワードが右腕に持つのは何製の義手？", media:null, audio:null, answer:"オートメイル", answers:"オートメイル,automail", nagaoType:"マンガ", explanation:null },
      { id:9, type:"kizyutsu", title:"Q9", text:"「Hunter×Hunter」でゴンの父親の名前は？", media:null, audio:null, answer:"ジン＝フリークス", answers:"ジン＝フリークス,ジン,ジンフリークス", nagaoType:"マンガ", explanation:null },
      { id:10, type:"kizyutsu", title:"Q10", text:"「SAO（ソードアート・オンライン）」の主人公の本名は？", media:null, audio:null, answer:"桐ヶ谷和人", answers:"桐ヶ谷和人,きりがやかずと,キリト", nagaoType:"アニメ", explanation:null },
      { id:11, type:"kizyutsu", title:"Q11", text:"「ハイキュー!!」で日向翔陽が所属する高校は？", media:null, audio:null, answer:"烏野高校", answers:"烏野高校,からすのこうこう,烏野", nagaoType:"アニメ", explanation:null },
      { id:12, type:"kizyutsu", title:"Q12", text:"「はじめの一歩」で主人公・幕之内一歩の♾️を描きながらブローを叩き込む必殺技は？", media:null, audio:null, answer:"デンプシーロール", answers:"デンプシーロール", nagaoType:"マンガ", explanation:null },
      { id:13, type:"kizyutsu", title:"Q13", text:"「ダイヤのA」で主人公・沢村栄純のポジションは？", media:null, audio:null, answer:"ピッチャー", answers:"ピッチャー,投手", nagaoType:"マンガ", explanation:null },
      { id:14, type:"kizyutsu", title:"Q14", text:"「ニセコイ」で一条楽が幼なじみとの約束の証として持つアイテムは？", media:null, audio:null, answer:"ペンダント(錠前)", answers:"錠前,ペンダント", nagaoType:"マンガ", explanation:null },
      { id:15, type:"kizyutsu", title:"Q15", text:"「ストライク・ザ・ブラッド」の主人公・暁古城の異名は？", media:null, audio:null, answer:"第四真祖", answers:"第四真祖,だいよんしんそ", nagaoType:"アニメ", explanation:null },
      { id:16, type:"kizyutsu", title:"Q16", text:"「IS（インフィニット・ストラトス）」で唯一ISを動かせる男性の名前は？", media:null, audio:null, answer:"織斑一夏", answers:"織斑一夏,おりむらいちか,一夏", nagaoType:"アニメ", explanation:null },
      { id:17, type:"kizyutsu", title:"Q17", text:"「クレヨンしんちゃん」の主人公一家が飼っている犬の名前は？", media:null, audio:null, answer:"シロ", answers:"シロ", nagaoType:"アニメ", explanation:null },
      { id:18, type:"kizyutsu", title:"Q18", text:"「べるぜバブ」の主人公・男鹿辰巳が育てる赤ちゃん悪魔の名前は？", media:null, audio:null, answer:"ベル坊", answers:"ベル坊,カイゼル・デ・エンペラーナ・ベルゼバブ4世", nagaoType:"マンガ", explanation:null },
      { id:19, type:"kizyutsu", title:"Q19", text:"「これはゾンビですか？」の主人公・相川歩が変身する職業は？", media:null, audio:null, answer:"魔装少女", answers:"魔装少女,まそうしょうじょ", nagaoType:"アニメ", explanation:null },
      { id:20, type:"kizyutsu", title:"Q20", text:"「東京レイヴンズ」の主人公・土御門春虎の式神の名前は？", media:null, audio:null, answer:"コン", answers:"コン", nagaoType:"アニメ", explanation:null },
      { id:21, type:"kizyutsu", title:"Q21", text:"「名探偵コナン」で主人公・工藤新一が薬で変身した後の名前は？", media:null, audio:null, answer:"江戸川コナン", answers:"江戸川コナン,えどがわこなん,コナン", nagaoType:"アニメ", explanation:null },
      { id:22, type:"kizyutsu", title:"Q22", text:"「MAJOR」の主人公・本田吾郎のポジションは？", media:null, audio:null, answer:"ピッチャー", answers:"ピッチャー,投手", nagaoType:"アニメ", explanation:null },
      { id:23, type:"kizyutsu", title:"Q23", text:"「スーパーロボット大戦OG」に登場するサイバスターのパイロット名は？", media:null, audio:null, answer:"マサキ・アンドー", answers:"マサキ・アンドー,マサキアンドー,アンドー", nagaoType:"アニメ", explanation:null },
      { id:24, type:"kizyutsu", title:"Q24", text:"「ハム太郎」でハム太郎の大好物は？", media:null, audio:null, answer:"ひまわりのたね", answers:"ひまわりのたね,ひまわりの種,向日葵の種", nagaoType:"アニメ", explanation:null },
      { id:25, type:"kizyutsu", title:"Q25", text:"「暗殺教室」で生徒たちが暗殺しようとするタコのような教師の名前は？", media:null, audio:null, answer:"殺せんせー", answers:"殺せんせー,ころせんせー", nagaoType:"アニメ", explanation:null },
      { id:26, type:"kizyutsu", title:"Q26", text:"「ペンギンの問題」の主人公ペンギンの名前は？", media:null, audio:null, answer:"木下ベッカム", answers:"木下ベッカム,きのしたべっかむ,ベッカム", nagaoType:"アニメ", explanation:null },
      { id:27, type:"kizyutsu", title:"Q27", text:"「銀魂」で坂田銀時・志村新八・神楽が働く屋号は？", media:null, audio:null, answer:"万事屋銀ちゃん", answers:"万事屋銀ちゃん,万事屋,よろずや", nagaoType:"マンガ", explanation:null },
      { id:28, type:"kizyutsu", title:"Q28", text:"「らんま1/2」で水をかぶると女になってしまう主人公の名前は？", media:null, audio:null, answer:"早乙女乱馬", answers:"早乙女乱馬,さおとめらんま,乱馬", nagaoType:"マンガ", explanation:null },
      { id:29, type:"kizyutsu", title:"Q29", text:"「ワンピース」でゾロの技「三千世界」は何刀流の技？", media:null, audio:null, answer:"三刀流", answers:"三刀流,さんとうりゅう,3,三", nagaoType:"マンガ", explanation:null },
      { id:30, type:"kizyutsu", title:"Q30", text:"「幽☆遊☆白書」の主人公・浦飯幽助が得意とする技は？", media:null, audio:null, answer:"霊丸", answers:"霊丸,れいがん", nagaoType:"マンガ", explanation:null },
      { id:31, type:"kizyutsu", title:"Q31", text:"パチスロ「モンスターハンター」シリーズのモチーフとなったゲームメーカーは？", media:null, audio:null, answer:"カプコン", answers:"カプコン,capcom", nagaoType:"スロット", explanation:null },
      { id:32, type:"kizyutsu", title:"Q32", text:"パチスロ「エヴァンゲリオン」シリーズで主人公が乗るロボットの名前は？", media:null, audio:null, answer:"エヴァンゲリオン初号機", answers:"初号機,エヴァ初号機,エヴァンゲリオン初号機", nagaoType:"スロット", explanation:null },
      { id:33, type:"kizyutsu", title:"Q33", text:"パチスロ「ルパン三世」シリーズでルパンの相棒である射撃の名手は誰？", media:null, audio:null, answer:"次元大介", answers:"次元大介,じげんだいすけ,次元", nagaoType:"スロット", explanation:null },
      { id:34, type:"kizyutsu", title:"Q34", text:"「押忍！番長」シリーズの主人公の名前は？", media:null, audio:null, answer:"金剛轟", answers:"轟金剛,とどろきこんごう,轟,とどろき", nagaoType:"スロット", explanation:null },
      { id:35, type:"kizyutsu", title:"Q35", text:"パチスロ「まどか☆マギカ」の主人公の名前は？", media:null, audio:null, answer:"鹿目まどか", answers:"鹿目まどか,かなめまどか,まどか", nagaoType:"スロット", explanation:null },
      { id:36, type:"kizyutsu", title:"Q36", text:"パチンコ「CR花の慶次」シリーズで主人公・前田慶次の愛馬の名前は？", media:null, audio:null, answer:"松風", answers:"松風,まつかぜ", nagaoType:"パチンコ", explanation:null },
      { id:37, type:"kizyutsu", title:"Q37", text:"パチスロ「バジリスク」シリーズの原作小説のタイトルは？", media:null, audio:null, answer:"甲賀忍法帖", answers:"甲賀忍法帖,こうがにんぽうちょう", nagaoType:"スロット", explanation:null },
      { id:38, type:"kizyutsu", title:"Q38", text:"「戦国乙女」シリーズでパチスロを出しているメーカーはどこ？", media:null, audio:null, answer:"平和", answers:"平和,HEIWA,ピーワールド", nagaoType:"スロット", explanation:null },
      { id:39, type:"kizyutsu", title:"Q39", text:"パチンコ「CR花の慶次」の主人公・前田慶次の二つ名は？", media:null, audio:null, answer:"傾奇者", answers:"傾奇者,かぶきもの", nagaoType:"パチンコ", explanation:null },
      { id:40, type:"kizyutsu", title:"Q40", text:"パチスロのウェイト時間は何秒？", media:null, audio:null, answer:"4.1秒", answers:"4.1秒,4.1,よんてんいちびょう", nagaoType:"スロット", explanation:null },
      { id:41, type:"kizyutsu", title:"Q41", text:"「ドラゴンボールZ」でフリーザの最終形態は第何形態？", media:null, audio:null, answer:"第4形態", answers:"第4形態,第四形態,4,四", nagaoType:"アニメ", explanation:null },
      { id:42, type:"kizyutsu", title:"Q42", text:"「NARUTO」でサスケが初めに使った炎遁の術の名前は？", media:null, audio:null, answer:"豪火球の術", answers:"豪火球の術,ごうかきゅうのじゅつ,火遁豪火球の術", nagaoType:"マンガ", explanation:null },
      { id:43, type:"kizyutsu", title:"Q43", text:"「ワンピース」でサンジの夢は何という海に行くこと？", media:null, audio:null, answer:"オールブルー", answers:"オールブルー", nagaoType:"マンガ", explanation:null },
      { id:44, type:"kizyutsu", title:"Q44", text:"「銀魂」で坂本辰馬が桂小太郎に贈った謎の宇宙生物の名前は？", media:null, audio:null, answer:"エリザベス", answers:"エリザベス", nagaoType:"マンガ", explanation:null },
      { id:45, type:"kizyutsu", title:"Q45", text:"「銀魂」で近藤勲が率いる組織の名前は？", media:null, audio:null, answer:"真選組", answers:"真選組,しんせんぐみ", nagaoType:"マンガ", explanation:null },
      { id:46, type:"kizyutsu", title:"Q46", text:"「進撃の巨人」でミカサの苗字は？", media:null, audio:null, answer:"アッカーマン", answers:"アッカーマン", nagaoType:"マンガ", explanation:null },
      { id:47, type:"kizyutsu", title:"Q47", text:"スロットで、2リール目を止めた時点でボーナス成立が確定することを何と呼ぶ？", media:null, audio:null, answer:"2確", answers:"2確,にかく,二確", nagaoType:"スロット", explanation:null },
      { id:48, type:"kizyutsu", title:"Q48", text:"「Hunter×Hunter」でゴンとキルアが受験したハンター試験、最終試験の内容は？", media:null, audio:null, answer:"組み手", answers:"組み手,くみて,格闘,バトル", nagaoType:"マンガ", explanation:null },
      { id:49, type:"kizyutsu", title:"Q49", text:"「僕のヒーローアカデミア」でオールマイトの本名は？", media:null, audio:null, answer:"八木俊典", answers:"八木俊典,やぎとしのり,トシノリ", nagaoType:"アニメ", explanation:null },
      { id:50, type:"kizyutsu", title:"Q50", text:"「SAO」でキリトとアスナが結婚して暮らした家があるフロアは第何層？", media:null, audio:null, answer:"第22層", answers:"第22層,22層,22,二十二層", nagaoType:"アニメ", explanation:null }
    ]
  },
  {
    id: "reborn",
    name: "家庭教師ヒットマンREBORN!",
    logo: null,
    logoText: "REBORN",
    desc: "ボンゴレファミリーの絆と炎、どこまで覚えているか試してみよ",
    color: "#ffaa00",
    questions: [
      { id:1, type:"kizyutsu", title:"Q1", text:"主人公・沢田綱吉序盤で呼ばれていたあだ名は？（○○ツナ）", media:null, audio:null, answer:"ダメツナ", answers:"ダメツナ,だめつな,だめ,ダメ", nagaoType:"未分類", explanation:null },
      { id:2, type:"kizyutsu", title:"Q2", text:"綱吉の家庭教師として現れる、赤ちゃんの姿をした最強の殺し屋の名前は？", media:null, audio:null, answer:"リボーン", answers:"リボーン,りぼーん", nagaoType:"未分類", explanation:null },
      { id:3, type:"kizyutsu", title:"Q3", text:"ボンゴレを英語で書くと？", media:null, audio:null, answer:"VONGOLA", answers:"VONGOLA,vongola", nagaoType:"未分類", explanation:null },
      { id:4, type:"kizyutsu", title:"Q4", text:"綱吉がハイパー化した際に炎をまとう部位はどこ？", media:null, audio:null, answer:"額", answers:"額,ひたい,頭", nagaoType:"未分類", explanation:null },
      { id:5, type:"kizyutsu", title:"Q5", text:"綱吉の同級生で、右腕的存在の不良少年の名前は？", media:null, audio:null, answer:"獄寺隼人", answers:"獄寺隼人,ごくでらはやと,獄寺", nagaoType:"未分類", explanation:null },
      { id:6, type:"kizyutsu", title:"Q6", text:"獄寺隼人の通り名（二つ名）は？", media:null, audio:null, answer:"スモーキング・ボム隼人", answers:"スモーキング・ボム隼人,スモーキングボム隼人,スモーキング・ボム,スモーキングボム,人間爆撃機,ハリケーン・ボム隼人,ハリケーンボム隼人,ハリケーン・ボム,ハリケーンボム", nagaoType:"未分類", explanation:null },
      { id:7, type:"kizyutsu", title:"Q7", text:"野球部に所属する、綱吉の陽気な友人の名前は？", media:null, audio:null, answer:"山本武", answers:"山本武,やまもとたけし,山本", nagaoType:"未分類", explanation:null },
      { id:8, type:"kizyutsu", title:"Q8", text:"山本武が使う武器は何？", media:null, audio:null, answer:"時雨金時", answers:"時雨金時,しぐれきんとき,刀,かたな,日本刀", nagaoType:"未分類", explanation:null },
      { id:9, type:"kizyutsu", title:"Q9", text:"雲雀恭弥の口癖として有名な、規則違反者に向けて言う言葉は？", media:null, audio:null, answer:"咬み殺す", answers:"咬み殺す,かみ殺す,かみころす,咬み殺すよ,かみ殺すよ,かみころすよ", nagaoType:"未分類", explanation:null },
      { id:10, type:"kizyutsu", title:"Q10", text:"雲雀恭弥が連れている小動物の名前は？", media:null, audio:null, answer:"ヒバード", answers:"ヒバード,ひばーど", nagaoType:"未分類", explanation:null },
      { id:11, type:"kizyutsu", title:"Q11", text:"綱吉をツナ君（またはツっ君）と呼ぶでヒロイン的存在の女の子の名前は？", media:null, audio:null, answer:"笹川京子", answers:"笹川京子,ささがわきょうこ,京子,きょうこ", nagaoType:"未分類", explanation:null },
      { id:12, type:"kizyutsu", title:"Q12", text:"綱吉の使用する武器は？", media:null, audio:null, answer:"グローブ", answers:"グローブ,ぐろーぶ", nagaoType:"未分類", explanation:null },
      { id:13, type:"kizyutsu", title:"Q13", text:"リボーンが主に銃に変身させる、緑色の爬虫類の相棒の名前は？", media:null, audio:null, answer:"レオン", answers:"レオン,れおん", nagaoType:"未分類", explanation:null },
      { id:14, type:"kizyutsu", title:"Q14", text:"未来編で登場する、ボンゴレ十代目ファミリーの敵となる組織の名前は？", media:null, audio:null, answer:"ミルフィオーレファミリー", answers:"ミルフィオーレファミリー,ミルフィオーレ", nagaoType:"未分類", explanation:null },
      { id:15, type:"kizyutsu", title:"Q15", text:"未来編のボスである、大空のマーレリングを所持する人物の名前は？", media:null, audio:null, answer:"白蘭", answers:"白蘭,びゃくらん", nagaoType:"未分類", explanation:null },
      { id:16, type:"kizyutsu", title:"Q16", text:"獄寺隼人の姉で、毒物のスペシャリストである殺し屋の名前は？", media:null, audio:null, answer:"ビアンキ", answers:"ビアンキ", nagaoType:"未分類", explanation:null },
      { id:17, type:"kizyutsu", title:"Q17", text:"ランボが所属する殺し屋一家の名前は？", media:null, audio:null, answer:"ボヴィーノファミリー", answers:"ボヴィーノファミリー,ボヴィーノ", nagaoType:"未分類", explanation:null },
      { id:18, type:"kizyutsu", title:"Q18", text:"ボンゴレ守護者「雲」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"雲雀恭弥", answers:"雲雀恭弥,ひばりきょうや,雲雀", nagaoType:"未分類", explanation:null },
      { id:19, type:"kizyutsu", title:"Q19", text:"ボンゴレ守護者「嵐」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"獄寺隼人", answers:"獄寺隼人,ごくでらはやと", nagaoType:"未分類", explanation:null },
      { id:20, type:"kizyutsu", title:"Q20", text:"ボンゴレ守護者「雨」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"山本武", answers:"山本武,やまもとたけし", nagaoType:"未分類", explanation:null },
      { id:21, type:"kizyutsu", title:"Q21", text:"ボンゴレ守護者「晴」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"笹川了平", answers:"笹川了平,ささがわりょうへい,了平", nagaoType:"未分類", explanation:null },
      { id:22, type:"kizyutsu", title:"Q22", text:"ボンゴレ守護者「雷」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"ランボ", answers:"ランボ", nagaoType:"未分類", explanation:null },
      { id:23, type:"kizyutsu", title:"Q23", text:"ボンゴレ守護者「霧」の役割を担う男性キャラクターは誰？", media:null, audio:null, answer:"六道骸", answers:"六道骸,ろくどうむくろ,骸", nagaoType:"未分類", explanation:null },
      { id:24, type:"kizyutsu", title:"Q24", text:"六道骸が閉じ込められている監獄の名前は？", media:null, audio:null, answer:"ヴィンディチェ", answers:"ヴィンディチェ", nagaoType:"未分類", explanation:null },
      { id:25, type:"kizyutsu", title:"Q25", text:"クローム髑髏の本名は？（苗字不明）", media:null, audio:null, answer:"凪", answers:"凪,なぎ", nagaoType:"未分類", explanation:null },
      { id:26, type:"kizyutsu", title:"Q26", text:"ボンゴレ守護者「嵐」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"獄寺隼人", answers:"獄寺隼人,ごくでらはやと", nagaoType:"未分類", explanation:null },
      { id:27, type:"kizyutsu", title:"Q27", text:"特殊暗殺部隊ヴァリアーのボスの名前は？", media:null, audio:null, answer:"ザンザス", answers:"ザンザス,ざんざす", nagaoType:"未分類", explanation:null },
      { id:28, type:"kizyutsu", title:"Q28", text:"綱吉たちが所属する中学校の名前は？", media:null, audio:null, answer:"並盛中学", answers:"並盛中学,並盛,なみもり", nagaoType:"未分類", explanation:null },
      { id:29, type:"kizyutsu", title:"Q29", text:"未来編で登場する、綱吉が最初に出会った女性の名前は？", media:null, audio:null, answer:"ラル・ミルチ", answers:"ラル・ミルチ,ラルミルチ", nagaoType:"未分類", explanation:null },
      { id:30, type:"kizyutsu", title:"Q30", text:"キャバッローネファミリーのディーノの二つ名は？", media:null, audio:null, answer:"跳ね馬", answers:"跳ね馬,はね馬,はねうま", nagaoType:"未分類", explanation:null },
      { id:31, type:"kizyutsu", title:"Q31", text:"ディーノの側近の名前は？", media:null, audio:null, answer:"ロマーリオ", answers:"ロマーリオ,ろまーりお", nagaoType:"未分類", explanation:null },
      { id:32, type:"kizyutsu", title:"Q32", text:"世界を保つための21個の至宝（ボンゴレリング、マーレリング、アルコバレーノのおしゃぶり）の総称は？", media:null, audio:null, answer:"7³（トゥリニセッテ）", answers:"7³,トゥリニセッテ", nagaoType:"未分類", explanation:null },
      { id:33, type:"kizyutsu", title:"Q33", text:"物語冒頭で綱吉が「ダメツナ」と呼ばれる理由になった、彼の性格・成績の特徴は何？", media:null, audio:null, answer:"落ちこぼれ", answers:"落ちこぼれ,おちこぼれ,ダメ", nagaoType:"未分類", explanation:null },
      { id:34, type:"kizyutsu", title:"Q34", text:"初代ボンゴレファミリーの当主（初代ボス）の名前は？", media:null, audio:null, answer:"ジョット", answers:"ジョット", nagaoType:"未分類", explanation:null },
      { id:35, type:"kizyutsu", title:"Q35", text:"初代ボンゴレファミリーで雲の守護者を務めた人物の名前は？", media:null, audio:null, answer:"アラウディ", answers:"アラウディ", nagaoType:"未分類", explanation:null },
      { id:36, type:"kizyutsu", title:"Q36", text:"初代ボンゴレファミリーで嵐の守護者を務めた人物の名前は？", media:null, audio:null, answer:"G", answers:"G,ジー", nagaoType:"未分類", explanation:null },
      { id:37, type:"kizyutsu", title:"Q37", text:"初代ボンゴレファミリーで雨の守護者を務めた人物の名前は？", media:null, audio:null, answer:"朝利雨月", answers:"朝利雨月,アサリ・ウゲツ,アサリ,雨月,あさりうげつ", nagaoType:"未分類", explanation:null },
      { id:38, type:"kizyutsu", title:"Q38", text:"初代ボンゴレファミリーで晴の守護者を務めた人物の名前は？", media:null, audio:null, answer:"ナックル", answers:"ナックル", nagaoType:"未分類", explanation:null },
      { id:39, type:"kizyutsu", title:"Q39", text:"初代ボンゴレファミリーで雷の守護者を務めた人物の名前は？", media:null, audio:null, answer:"ランポウ", answers:"ランポウ", nagaoType:"未分類", explanation:null },
      { id:40, type:"kizyutsu", title:"Q40", text:"初代ボンゴレファミリーで霧の守護者を務めた人物の名前は？", media:null, audio:null, answer:"デイモン・スペード", answers:"デイモン・スペード,D・スペード,デイモンスペード,デイモン,スペード", nagaoType:"未分類", explanation:null },
      { id:41, type:"kizyutsu", title:"Q41", text:"ボンゴレファミリーはもともと何のための組織として結成された？", media:null, audio:null, answer:"自警団", answers:"自警団,じけいだん", nagaoType:"未分類", explanation:null },
      { id:42, type:"kizyutsu", title:"Q42", text:"獄寺隼人が主に武器として使うものは？", media:null, audio:null, answer:"ダイナマイト", answers:"ダイナマイト", nagaoType:"未分類", explanation:null },
      { id:43, type:"kizyutsu", title:"Q43", text:"フータ・デッレ・ステッレの特技は、あらゆる物事に何をつけることか？", media:null, audio:null, answer:"ランキング", answers:"ランキング", nagaoType:"未分類", explanation:null },
      { id:44, type:"kizyutsu", title:"Q44", text:"イーピンの出身はどこの国？", media:null, audio:null, answer:"中国", answers:"中国,ちゅうごく", nagaoType:"未分類", explanation:null },
      { id:45, type:"kizyutsu", title:"Q45", text:"綱吉の母親の名前は？", media:null, audio:null, answer:"沢田奈々", answers:"沢田奈々,奈々,なな,ナナ", nagaoType:"未分類", explanation:null },
      { id:46, type:"kizyutsu", title:"Q46", text:"綱吉の父親の名前は？", media:null, audio:null, answer:"沢田家光", answers:"沢田家光,家光,いえみつ,イエミツ", nagaoType:"未分類", explanation:null },
      { id:47, type:"kizyutsu", title:"Q47", text:"笹川京子の親友の名前は？", media:null, audio:null, answer:"黒川花", answers:"黒川花,くろかわはな,ハナ,花,はな,黒川,くろかわ", nagaoType:"未分類", explanation:null },
      { id:48, type:"kizyutsu", title:"Q48", text:"シモン一族の末裔にあたる転校生のボスの名前は？", media:null, audio:null, answer:"古里炎真", answers:"古里炎真,炎真,エンマ,えんま", nagaoType:"未分類", explanation:null },
      { id:49, type:"kizyutsu", title:"Q49", text:"綱吉たちを未来へ送った実は味方だった人物の名前は？", media:null, audio:null, answer:"入江正一", answers:"入江正一,いりえしょういち,正一", nagaoType:"未分類", explanation:null },
      { id:50, type:"kizyutsu", title:"Q50", text:"X BURNERを完成させるため、コントタクトレンズを作成したの名前は？", media:null, audio:null, answer:"スパナ", answers:"スパナ", nagaoType:"未分類", explanation:null },
      { id:51, type:"kizyutsu", title:"Q51", text:"白蘭が好んで食べているお菓子は何？", media:null, audio:null, answer:"マシュマロ", answers:"マシュマロ", nagaoType:"未分類", explanation:null },
      { id:52, type:"kizyutsu", title:"Q52", text:"ヴァリアーで「雲」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"雲雀恭弥", answers:"雲雀恭弥,ひばりきょうや,雲雀", nagaoType:"未分類", explanation:null },
      { id:53, type:"kizyutsu", title:"Q53", text:"ヴァリアーで「嵐」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"ベルフェゴール", answers:"ベルフェゴール,ベル", nagaoType:"未分類", explanation:null },
      { id:54, type:"kizyutsu", title:"Q54", text:"ヴァリアーで「雨」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"スクアーロ", answers:"スクアーロ", nagaoType:"未分類", explanation:null },
      { id:55, type:"kizyutsu", title:"Q55", text:"ヴァリアーで「晴」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"ルッスーリア", answers:"ルッスーリア", nagaoType:"未分類", explanation:null },
      { id:56, type:"kizyutsu", title:"Q56", text:"ヴァリアーで「雷」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"レヴィ・ア・タン", answers:"レヴィ・ア・タン,レヴィ", nagaoType:"未分類", explanation:null },
      { id:57, type:"kizyutsu", title:"Q57", text:"ヴァリアーで「霧」の役割を担うキャラクターは誰？（ヴァリアーでの名前で）", media:null, audio:null, answer:"マーモン", answers:"マーモン", nagaoType:"未分類", explanation:null },
      { id:58, type:"kizyutsu", title:"Q58", text:"アルコバレーノで初代「大空」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"ルーチェ", answers:"ルーチェ", nagaoType:"未分類", explanation:null },
      { id:59, type:"kizyutsu", title:"Q59", text:"アルコバレーノで「雲」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"スカル", answers:"スカル", nagaoType:"未分類", explanation:null },
      { id:60, type:"kizyutsu", title:"Q60", text:"アルコバレーノで「嵐」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"風（フォン）", answers:"風（フォン）,風,フォン", nagaoType:"未分類", explanation:null },
      { id:61, type:"kizyutsu", title:"Q61", text:"アルコバレーノで「雨」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"コロネロ", answers:"コロネロ", nagaoType:"未分類", explanation:null },
      { id:62, type:"kizyutsu", title:"Q62", text:"アルコバレーノで「晴」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"リボーン", answers:"リボーン", nagaoType:"未分類", explanation:null },
      { id:63, type:"kizyutsu", title:"Q63", text:"アルコバレーノで「雷」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"ヴェルデ", answers:"ヴェルデ", nagaoType:"未分類", explanation:null },
      { id:64, type:"kizyutsu", title:"Q64", text:"アルコバレーノで「霧」の役割を担うキャラクターは誰？", media:null, audio:null, answer:"バイパー", answers:"バイパー", nagaoType:"未分類", explanation:null },
      { id:65, type:"kizyutsu", title:"Q65", text:"初代「大空」のアルコバレーノの娘であり、現在の大空の母親であるの名前は？", media:null, audio:null, answer:"アリア", answers:"アリア", nagaoType:"未分類", explanation:null },
      { id:66, type:"kizyutsu", title:"Q66", text:"ジッリョネロファミリーのボスであり、アルコバレーノ達を生き返らせるため亡くなった人物は？", media:null, audio:null, answer:"ユニ", answers:"ユニ", nagaoType:"未分類", explanation:null },
      { id:67, type:"kizyutsu", title:"Q67", text:"ブーメランを武器とする青い色のハイパー死ぬ気モードで戦う人物名前は？", media:null, audio:null, answer:"バジル", answers:"バジル", nagaoType:"未分類", explanation:null },
      { id:68, type:"kizyutsu", title:"Q68", text:"山本武の父親が営む店は何の店？", media:null, audio:null, answer:"寿司屋", answers:"寿司屋,すしや", nagaoType:"未分類", explanation:null },
      { id:69, type:"kizyutsu", title:"Q69", text:"山本武の父親の名前は？", media:null, audio:null, answer:"山本剛", answers:"山本剛,やまもとつよし", nagaoType:"未分類", explanation:null },
      { id:70, type:"kizyutsu", title:"Q70", text:"ランボが物語に最初に登場した際の見た目の年齢は？", media:null, audio:null, answer:"5歳", answers:"5歳,五歳", nagaoType:"未分類", explanation:null },
      { id:71, type:"kizyutsu", title:"Q71", text:"獄寺隼人が綱吉を呼ぶときの呼び方は？", media:null, audio:null, answer:"十代目", answers:"十代目,じゅうだいめ", nagaoType:"未分類", explanation:null },
      { id:72, type:"kizyutsu", title:"Q72", text:"綱吉のボックス武器であるライオンの名前は？", media:null, audio:null, answer:"ナッツ", answers:"ナッツ", nagaoType:"未分類", explanation:null },
      { id:73, type:"kizyutsu", title:"Q73", text:"獄寺隼人のボックス武器である猫の名前は？", media:null, audio:null, answer:"瓜", answers:"瓜,うり,ウリ", nagaoType:"未分類", explanation:null },
      { id:74, type:"kizyutsu", title:"Q74", text:"山本武のボックス武器である犬の名前は？", media:null, audio:null, answer:"次郎", answers:"次郎,じろう,雨犬", nagaoType:"未分類", explanation:null },
      { id:75, type:"kizyutsu", title:"Q75", text:"山本武のボックス武器であるツバメの名前は？", media:null, audio:null, answer:"小次郎", answers:"小次郎,こじろう,雨ツバメ", nagaoType:"未分類", explanation:null },
      { id:76, type:"kizyutsu", title:"Q76", text:"ディーノが率いる一族の名前は？", media:null, audio:null, answer:"キャバッローネファミリー", answers:"キャバッローネファミリー,キャバッローネ", nagaoType:"未分類", explanation:null },
      { id:77, type:"kizyutsu", title:"Q77", text:"「家庭教師ヒットマンREBORN!」が連載されていた雑誌は？", media:null, audio:null, answer:"週刊少年ジャンプ", answers:"週刊少年ジャンプ,少年ジャンプ,ジャンプ", nagaoType:"未分類", explanation:null },
      { id:78, type:"kizyutsu", title:"Q78", text:"「家庭教師ヒットマンREBORN!」の作者の名前は？", media:null, audio:null, answer:"天野明", answers:"天野明,あまのあきら", nagaoType:"未分類", explanation:null }
    ]
  }
];

// room-play.htmlからアクセスできるようwindowに公開
if (typeof window !== 'undefined') {
  window.DEFAULT_GENRES = DEFAULT_GENRES;
}
